version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - forkflix-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-admin-key.json
      - CORS_ORIGINS=http://localhost:80,http://localhost:3000
    volumes:
      - ./firebase/firebase-admin-key.json:/app/firebase-admin-key.json:ro
      - backend-logs:/app/logs
      - backend-tmp:/app/tmp
    restart: unless-stopped
    networks:
      - forkflix-network

volumes:
  backend-logs:
  backend-tmp:

networks:
  forkflix-network:
    driver: bridge