version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-admin-key.json
    volumes:
      - ./backend:/app
      - ./firebase/firebase-admin-key.json:/app/firebase-admin-key.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload